version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app:/app

    php:
        image: php:fpm-alpine
        volumes:
            - ./app:/app
